### ISSUE TITLE
Reading a nested array of objects

### ISSUE THREAD

**Issue by rouson** [Goddard-Fortran-Ecosystem/yaFyaml#11]
I'm wondering if yaFyaml can be used to read the following JSON file:
```json
{ "dag" : { "vertices" : [ {"depends_on" : []}, {"depends_on" : [1]} ] } }
```
using something similar to the following program
```fortran
program main
   use yafyaml, only : Parser, Configuration, FileStream
   implicit none

   type vertex
     integer, allocatable :: depends_on(:)
   end type

   type dag
     type(vertex), allocatable :: vertices(:)
   end type

   type(dag) d
   type(Parser) p
   type(Configuration) c

   p = Parser('core')
   c = p%load(FileStream('object-array.json'))
   call c%get(d%vertices, 'dag', 'vertices')   ! <----- What goes here? -----

   sync all
   if (this_image()==1) print *,"Test passed"
end program
```
Is this currently possible?  I'm imagining that the solution involves using the gFTL Vector class.

**Comment by tclune** [comment]
As you are inferring, if you don't dive into a Configuration object all the way down to a leaf node, then there is not in general a corresponding intrinsic type.   In theory some sequences can be associated with Fortran arrays but since that cannot be assumed in general, yaFyaml does not even attempt to do so.   Instead sequences are internally represented as UnlimitedVector containers and mappings as StringUnlimitedMap.   In both cases the elements of the containers are declared as CLASS(*), ALLOCATABLE, and in the case of Vector, wrapped in an internal type to enable array access.   But the get() method you are using actually still returns a Configuration object that would internally have a pointer to the vector under vertices.

In theory, yaFyaml would let you drill down to the intrinsic integers inside your vertex derived type:
```f90
ALLOCATE(nodes(2))
nodes(1)%depends_on = c%get('dag','vertices',1,'depends_on')
nodes(2)%depends_on = c%get('dag','vertices',2,'depends_on')
```
but this assumes that various bits are already allocated.  (And an empty array is probably not covered by the unit tests, so be prepared to find a ~bug~ unsupported feature.

In a more realistic case, you would not know how many nodes are in the file and would expect to find that from the configuration:
```f90
type(Configuration) :: subconfig
call c%get(subconfig, 'dag', 'vertices')
```
We assume subconfig is a sequence, but need its size.  Unfortunately, there is not (yet) a handy size() method at this level.    (Next feature!)   For now we must resort to class(*) and get the actual vector:
```f90
use gFTL_UnlimitedVector
class(*), pointer :: node
integer :: n_nodes
call c%get_node_at_selector(node, 'dag', 'vertices')
select type (node)
class is (UnlimitedVector)
   n_nodes = node%size()
   ! Now you can use the earlier code to fill things in.
class default
   error stop
end select
```

Part of the difficulty here is that the ultimate components of your derived types are Fortran arrays.   If these were instead a growable container, ala, vectors then a (slightly) more natural access can be done where your data structures grow as you traverse the configuration tree:
```f90
use gFTL_IntegerVector
type :: dag
   type(IntegerVector) :: vertices
end type
! <boiler plate gFTL include code here>
type(DagVector) :: nodes, node
type(ConfigurationIterator) :: iter
type(Configuration) :: subconfig

call c%get(subconfig, 'dag', 'vertices')
iter = subconfig%begin()
do while (iter /= subconfig%end())
   call process_node(iter%get(), node)
   call nodes%push_back(node)
   call iter%next()
end do

contains

subroutine process_node(config, node)
    type(Configuration), intent(in) :: config
    type(Dag), intent(out) :: node

    type(ConfigurationIterator) :: iter
    type(Configuration) :: subconfig
 
     iter=config%begin()
     do while (iter /= config%end())
          subconfig = iter%get()
          i = subconfig%at('depends_on')
          call node%push_back(i)
          call iter%next()
     end do
     call nodes%pushback(node)
end subroutine
```

**Comment by rouson** [comment]
@tclune thanks for the detailed reply.  If I understand what you wrote, then it should wore to replace the comment `! Now you can use the earlier code to fill things in.` with the following:
```fortran
allocate(d%vertices(n_nodes))
do i=1, n_nodes
   d%nodes(i)%depends_on = c%get('dag','vertices',i,'depends_on')
end do
```
I'll give this a shot and close the issue if it works.

**Comment by rouson** [comment]
@tclune everything works!  Thank for your help and for writing a great collection of libraries.  Even the zero-sized array read works fine.  I've always loved the way Fortran's zero-sized arrays so often work naturally without any special-casing.  I can now read the following JSON file:
```json
{ "dag" : { "vertices" : [ {"depends_on" : [2,3]}, {"depends_on" : [3]}, {"depends_on" : []} ] } }
```
with the following program compiled with the `nagfor` 7.0 and `gfortran` 9.3.0:
```fortran
program main
  !! Test the reading of a JSON file with a nested array of objects
  use yafyaml, only : Parser, Configuration, FileStream
  use gFTL_UnlimitedVector, only : UnlimitedVector
  implicit none

  type vertex
    integer, allocatable :: depends_on(:)
  end type

  type dag
    type(vertex), allocatable :: vertices(:)
  end type

  type(dag) d
  type(Parser) p
  type(Configuration) c, subconfig

  class(*), pointer :: dag_vertices=>null(), dag_vertices_i_depends_on=>null()
  integer :: i, j

  p = Parser('core')
  c = p%load(FileStream('nested-object-array.json'))
  call c%get_node_at_selector(dag_vertices, 'dag', 'vertices')

  select type (dag_vertices)
  class is (UnlimitedVector)

    allocate(d%vertices(dag_vertices%size()))

    do i=1,size(d%vertices)

      call c%get(subconfig, 'dag', 'vertices', i)
      call subconfig%get_node_at_selector(dag_vertices_i_depends_on, 'depends_on')

      select type (dag_vertices_i_depends_on)
      class is (UnlimitedVector)

        allocate(d%vertices(i)%depends_on(dag_vertices_i_depends_on%size()))

        do j = 1,size(d%vertices(i)%depends_on)
          d%vertices(i)%depends_on(j) = c%at('dag','vertices',i,'depends_on',j)
        end do
      class default
        error stop "unexpected dag_vertices_i_depends_on class"
      end select

    end do

  class default
    error stop "unexpected dag_vertices class"
  end select

  if ( any(d%vertices(1)%depends_on /= [2,3]      )) error stop "dag%vertices(1) incorrect"
  if ( any(d%vertices(2)%depends_on /= [3]        )) error stop "dag%vertices(2) incorrect"
  if ( any(d%vertices(3)%depends_on /= [integer::])) error stop "dag%vertices(3) incorrect"

  sync all
  if (this_image()==1) print *,"Test passed"
end program
```
