### ISSUE TITLE
[QUESTION] Plan for anchors

### ISSUE THREAD

**Issue by lizziel** [Goddard-Fortran-Ecosystem/yaFyaml#17]
Do you have an idea of when anchors will be introduced into yaFyaml?

**Comment by tclune** [comment]
I have something very basic working and could push and release if it is useful to you.     Basically it has anchors working (to the limited extent I have tested),  and an alias will work so long as it is just using the entire anchor.   It does not do the more general situation where the alias only brings in the components of the anchor that are not already specified.       This requires a mapping merge  which probably will be relatively easy.  (Would be even easier if I did not need to tiptoe around compilers breaking when doing a deep copy of a nested structure.)

I got distracted because I also wanted to introduce non-string keys for mappings.   At the very least, integers would be useful, but wanted to see how hard it would be to even allow sequences and mappings to be keys.   Got something sketched out, and then realized that gFTL really needs an extension to do this "right".   And gFTL is ... difficult to change.   So I started a major redesign of how gFTL include files are handled and generated.   All going well, but it is a long, long detour from the functionality you want.

If the limited anchor satisfies your use case, let me know.  Otherwise, I'll do my best to set gFTL aside for a few days and attempt an implementation for a merge for mappings.

**Comment by tclune** [comment]
Made some useful progress this evening.   No idea how fragile it is, but I now have a unit test that does a partial merge successfully.    Unfortunately, at this point the Python reference implementation is fairly useless to me (design has diverged at the higher levels), so concrete (but small!) use cases will be very useful for further testing.

Stay "squeaky".

**Comment by lizziel** [comment]
Thanks @tclune! The file that I need to read is this: https://github.com/geoschem/geos-chem/blob/dev/12.9.0/Headers/species_database.yml

Here's a sample from the file that shows how we are using anchors:
https://github.com/geoschem/geos-chem/blob/fdbc929d2d50276154580c7a63f5bed9f59b2355/Headers/species_database.yml#L170-L195

**Comment by lizziel** [comment]
Looking through the file, it does not appear we have any cases that would require a mapping merge. The anchor properties appear to only contain properties not meant to be over-written by whatever uses the anchor. So perhaps yaFyaml will already work as is.

**Comment by tclune** [comment]
Technically your use case actually does use the "merge key", and while you are only appending to the anchor, it still exercises most of the machinery I added yesterday.        I'm going to rig up a driver and try your code shortly.    If that works I'll risk doing the same thing with gfortran ... 

Thank you for the use case!

**Comment by lizziel** [comment]
Excellent, this is incredibly helpful.

**Comment by tclune** [comment]
Well, I was a bit astonished, but the the tool appears to have fully ingested your file without complaint.  (Took about 20 seconds, which means I may need to be concerned more about performance than I have been.)   Unfortunately, something overflowed on the JSON output at the end which was how I was going to inspect the results.   Hopefully that problem can be found quickly.

**Comment by tclune** [comment]
OK - the output issue was simply a limitation of the compiler I was using (NAG).   I have a workaround, but even that was not necessary for ifort.  I am attaching the JSON output in case you want to check more carefully, but my spot checks indicate the file was correctly processed.   (But clearly my JSON formatter needs some work to make it a bit friendlier.)


[out.txt](https://github.com/Goddard-Fortran-Ecosystem/yaFyaml/files/4833076/out.txt)

**Comment by tclune** [comment]
Alas,  the extension breaks gfortran.  Possibly just the test.  But something is amiss.

**Comment by tclune** [comment]
OK - found a (marginally) tolerable workaround for gfortran and it appears to work.   Have also improved the JSON formatting for large data sets.  Need to update the unit tests and clean up and all that.  I should be able to push over the weekend.  If you don't see a release, be squeaky on Monday.

**Comment by lizziel** [comment]
Thanks Tom, this is great. I'll update yaFyaml when I update MAPL again, assuming next week. Then I'll give it a go in GEOS-Chem.

**Comment by tclune** [comment]
v0.4.0 is supports anchors&aliases.   Also has much improved JSON formatting.

(cc'ing @rouson )
