### ISSUE TITLE
Need an NVHPC.cmake file

### ISSUE THREAD

**Issue by cponder** [Goddard-Fortran-Ecosystem/yaFyaml#44]
I can help fill in the contents if you need.
Looking at the GNU.cmake & Intel.cmake files, I don't see the names of the compilers being set.
Are they specified on the command-line, or buried in the rest of the framework somewhere?

**Comment by tclune** [comment]
We're probably not doing it in the canonical way.  We allow cmake to determine the compiler from the environment -- I think it checks in various ways to make that determination.   So rather than specifying a compiler, we load an environment in which a given compiler is the default.    Exact logic hidden inside CMake but might be documented.

**Comment by mathomp4** [comment]
@cponder We include the compiler flags via this code:

https://github.com/Goddard-Fortran-Ecosystem/yaFyaml/blob/171c93c93577019e21ec7828c2c61f7bb16d996c/CMakeLists.txt#L15-L19

so we trigger off what CMake sees as the `CMAKE_Fortran_COMPILER_ID`. Now that comes from what CMake gathers from `CMAKE_Fortran_COMPILER` which, if you don't set in the environment or command line, is then taken from `$FC` from the environment. 

So, if it detects you are using `nvfortran` then CMake sets `CMAKE_Fortran_COMPILER_ID` to `NVHPC` and then we do `include(NVHPC)` and that then searches the `CMAKE_MODULE_PATH` for a file called `NVHPC.cmake` which is in `cmake/`

I'm not sure what happens if neither is set. My guess is CMake will look for `fc` or `f90`? 🤷🏼
