### ISSUE TITLE
Potential bug: Only a subset of a string mapping is being read from a YAML file

### ISSUE THREAD

**Issue by yantosca** [Goddard-Fortran-Ecosystem/yaFyaml#5]
Hi -- this is Bob Yantosca here.  I have been poking around with yaFyaml as we plan on using it as the YAML parser for GEOS-Chem.  We are converting our GEOS-Chem species database from hardcoded F90 statements to YAML input (so that we can use the same file in Fortran and Python).

I was able to build yaFyaml as well as gFTL and gFTL-shared on my cluster.  That was pretty straightforward.  I then started working through the examples` simple.F90` and `iterators.F90`.  Also very straightforward.  I am testing in my own CMake-backed test-rig, which I have as a private Github repo (I can let you have access if you want).  

I noticed one weird thing, and I wasn't sure if I was doing something wrong, or if this a known issue.  It seems that yaFyaml does not return all characters of a YAML string mapping.  For example, following the simple.F90 example, I set up this test program: 

- [simple2.F.txt](https://github.com/Goddard-Fortran-Ecosystem/yaFyaml/files/4471879/simple2.F.txt)

which reads this YAML file:
- [simple.yaml.txt](https://github.com/Goddard-Fortran-Ecosystem/yaFyaml/files/4471882/simple.yaml.txt)

Long story short, in the YAML file I have this string mapping:
```
name: ABCDEFGHIJKLMONPQRSTUVWXYZ
```
but when I run the program I get:
```
 ### name is: ABCD
```
I am not sure if you have seen this kind of behavior before.  I did see some comments in the yaFyaml code about gfortran 9.2 having some wonky behavior with strings.  I am using a software stack with gfortran 9.2.0 that I built via Spack, so that co

Also if it's helpful, here is the CMake output log:

- [CMakeOutput.log.txt](https://github.com/Goddard-Fortran-Ecosystem/yaFyaml/files/4471913/CMakeOutput.log.txt)

I was also able to replicate this issue with ifort 17.0.4 as well.

In any case, if this is a known issue and you have a workaround, then let me know.  If I come across any other issues during my testing I'll post them here.

Best --  Bob Y.

**Comment by tclune** [comment]
@yantosca I'll take a look.    There were some updates pushed yesterday that fix some issues with gFortran.    I've only used 19.0.5 and later for testing with ifort.   I'll try to replicate your example in that environment to pin down whether this is a compiler bug or a yaFyaml bug.

**Comment by tclune** [comment]
OK under ifort 19.0.5 the output is 
```
./a.out
 ### name is: ABCDEFGHIJKLMONPQRSTUVWXYZ
```

Same output with gfortran 9.3 on my OS X laptop.  (We are asking computing  center to install 9.3 on discover, but it is not there yet.)    It also works under unreleased gfortran 10.0.     

We have identified problems under gfortran 9.2 and 9.1 but have not isolated them into a clean reproducer to submit.  (And not much point since 9.3 apparently fixed them.)    Note that getting gfortran to work even under 9.3 was a real marathon of debugging weird memory corruption issues and postulating workrounds.     There are some fundamental issues with gfortran for deferred length strings used in an unlimited polymorphic context.   

Can your team upgrade to 9.3 going forward?

**Comment by yantosca** [comment]
Hi Tom.  Thanks for checking. While it would be straightfoward for the GCST to adopt the latest Fortran compiler for testing, this is a requirement that we would like to avoid placing on our GEOS-Chem user community.  We try to keep GEOS-Chem compatible with a wide range of recent compiler versions (gcc/gfortran 6+ and most versions of ifort).  This is because it would be potentially disruptive to our users to have to abandon whatever software versions they have been using to install a new software stack.

Would it be possible to install a workaround for the more recent gfortran versions when you get a chance?   I know that is extra work but it would be potentially very useful since we eventually plan to use yaFyaml in several areas of GEOS-Chem, as we transition config file formats to YAML.

**Comment by tclune** [comment]
@yantosca  Unfortunately there is not even a clear path to work around the compiler issues.   "Fixing" probably at least requires a completely fundamental redesign of the internal representation of the config.         The two things that were known to break even the latest GFortran are:
1. CLASS(*) combined with CHARACTER(:), ALLOCATABLE  and 
2. Copying deep data structures (dictionaries of dictionaries that are fundamental to YAML representation).   

To workaround (1) I wrapped all such strings inside a derived type STRING.   For (2), I had to replace several FUNCTIONs with SUBROUTINEs.    

The worst of it was, the original implementation worked with NAG and Intel and most of the unit tests passed with gfortran.   It was the more complicated examples that revealed just how broken the compiler is.   And the failures were non-reproducible.   Crash one time, wrong answer the next, and passing on the 3rd attempt.   It was "fun" to fix.

There may be a few more of functions that could be converted to subroutines that are fine with 9.3 but break the earlier versions.   If so then a small workaround might be possible over the coming weekend.

Failing that?   I'm happy to have others try to diagnose and determine just what the compiler is struggling with.   If we understand that, then we can at least guess at a workaround.

**Comment by tclune** [comment]
Update:   Our main cluster now has 9.3 installed and ... yaFyaml fails its unit tests there as well.   So ... now I have no choice but to explore further workarounds.  (Very odd that the tests pass on OS X but not Linux - usually things are the other way around.)

And if those workarounds help other versions of gfortran, all the better.

(Pinging @mathomp4 so that he sees this info.)

**Comment by tclune** [comment]
Update:  The failing unit tests are exercising the layer that can print out a config in JSON format.   This is mostly a convenience and aid for debugging.     The actual examples (now expanded to include the reproducer have been demonstrated to work with:

| OS | Compiler | Version |
| --- | --- | --- |
| OS X | NAG | 7.0_7015 |
| OS X | GNU | 9.3 |
| OS X | GNU | 10.0 (exp) |
| OS X | Intel | 18.0.5 |
| OS X | Intel | 19.0.5 |
| Linux | GNU | 9.3* |
| Linux | GNU | 9.2* |
| Linux | GNU | 8.3* |

Failures:

| OS | Compiler | Version | Comment |
| --- | --- | --- | --- |
| Linux | GNU | 7.3 | build fails badly |
| Linux | GNU | 7.4 | probable compiler installation issue on SLES 12 |
| Linux | GNU | 8.3 | DTIO fails, but examples work |
| Linux | GNU | 9.2 | DTIO fails, but examples work |
| Linux | GNU | 9.3 | DTIO fails, but examples work |

Also note that the unit testing framework itself will not build before GFortran 8.3.

Conclusion:  Porting to GFortran 6 or even 7 is just not feasible.    I'm happy to accept external mods that allow this to build.  (But may require them to live on a branch if the impact to the design is severe.)

Another option for you could be to just put Fortran wrappers around a C++ YAML layer.   This is what the JEDI project is doing for their data assimilation effort.   I chose the other route because I want to use my gFTL containers to interoperate between various layers of GEOS.
